// ./sheet 子路径入口：具名转出 @infinitable/sheet 全部公共 API（与
// packages/sheet/src/index.ts 白名单同步维护，禁止星号导出转售）。
// 导出判据与主入口一致（判据、逐项清单与移出项过渡方案见 agent-docs/apis/exports.md）；
// 符号集合由 tests/public-surface.test.ts 快照冻结，增删导出必须显式改快照。
// 公式引擎 API 不在此转售——下游如需直接 import '@infinitable/formulas'，
// 本子路径只覆盖电子表格核心（模型/命令/IO/SheetGrid 适配）。
export {
  cellKey,
  colIndexToName,
  colNameToIndex,
  parseAddress,
  formatAddress,
  createRange,
  parseRange,
  formatRange,
  rangesEqual,
  rangesIntersect,
  rangeContainsAddress,
  boundingBox,
  iterateRange,
  type CellAddress,
  type CellRange,
  NUMERIC_TEXT_RE,
  normalizeInputValue,
  inferCellType,
  isEmptyCellData,
  cellDataEqual,
  CellStore,
  type CellType,
  type CellValue,
  type CellData,
  type CellSnapshotItem,
  cellMetaKey,
  cellMetaKeyFrom,
  cloneCellMetaPayload,
  cellMetaPayloadEqual,
  type CellMetaSnapshotItem,
  CellMetaStore,
  CELL_READONLY_META_NAMESPACE,
  BORDER_SIDES,
  BORDER_STYLE_WIDTH,
  BORDER_EDGE_DEFAULTS,
  FONT_STYLE_KEYS,
  ALIGN_STYLE_KEYS,
  type BorderLineStyle,
  type BorderSide,
  type BorderEdge,
  type HorizontalAlign,
  type VerticalAlign,
  type CellFont,
  type CellAlign,
  type CellStyle,
  type StyleId,
  type CellStylePatch,
  type NumFmt,
  StylePool,
  composeCellStyles,
  buildBorderPresetItems,
  type BorderPreset,
  type BorderPresetItem,
  MergeManager,
  type MergedCellKind,
  type CellInfo,
  type MergeResult,
  SelectionModel,
  type SelectionState,
  computeFillTargetRange,
  generateFill,
  type FillDirection,
  type GenerateFillOptions,
  findAll,
  findNext,
  findNextFrom,
  findPrev,
  findPrevFrom,
  type FindOptions,
  type FindMatch,
  Sheet,
  type FrozenState,
  type SheetSnapshot,
  type SheetEvents,
  Workbook,
  type WorkbookEvents,
  type AddSheetOptions,
  type AddSheetCellInput,
  FormulaEngine,
  HistoryManager,
  type HistoryState,
  type PatchDirection,
  type CellPatch,
  type MergePatch,
  type StructureChange,
  type StructurePatch,
  type SnapshotPatch,
  type ImagePatch,
  type CellMetaPatch,
  type AxisStylePatch,
  type Patch,
  type Mutation,
  type CommandResult,
  type CommandContext,
  type Command,
  type SetCellValueItem,
  type SetCellValueParams,
  SetCellValueCommand,
  type SetCellFormulaParams,
  SetCellFormulaCommand,
  type SetCellStyleItem,
  type SetCellStyleParams,
  SetCellStyleCommand,
  type SetAxisStyleItem,
  type SetAxisStyleParams,
  SetAxisStyleCommand,
  type InsertCellsParams,
  InsertCellsCommand,
  type MergeCellsParams,
  MergeCellsCommand,
  type UnmergeCellsParams,
  UnmergeCellsCommand,
  type MergeCellsBatchParams,
  MergeCellsBatchCommand,
  type InsertImageParams,
  InsertImageCommand,
  type RemoveImageParams,
  RemoveImageCommand,
  type ImageUpdateFields,
  type UpdateImageParams,
  UpdateImageCommand,
  type SetCellMetaParams,
  SetCellMetaCommand,
  type ClearCellMetaParams,
  ClearCellMetaCommand,
  defaultCommandRegistry,
  CommandRegistry,
  createImageId,
  cloneImageAnchor,
  cloneSheetImage,
  type SheetImageType,
  type SheetImageAnchor,
  type SheetImage,
  type ImageInput,
  exportWorkbookXlsx,
  exportSheetXlsx,
  exportSheetCsv,
  importXlsx,
  importCsv,
  replaceWorkbookWithSnapshots,
  type SheetReplaceItem,
  TypedEventEmitter,
  type CellRenderer,
  type CellRenderTarget,
  SheetGrid,
  type ResolveCellRenderer,
  type SheetGridOptions,
  // SheetGridOptions.scrollbar 对象形态（core 同形再导出；mode: 'native' 原生滚动条档）
  type ScrollbarOptions,
  type ResolveCellStyleHook,
  type ResolveDisplayValue,
  type SheetGridContextMenuInfo,
  type SheetGridContextMenuKind,
  type SheetGridHeaderOptions,
  type GridCellEditor,
  type GridEditorRect,
  type GridEditorSession,
  type SheetGridEditorsOptions,
} from '@infinitable/sheet'
